name: test-application
on: [pull_request]
jobs:
    test-application:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                  python-version: '3.10'
            - run: pip install -r infra/requirements.txt
            - run: python manage.py test